### ISSUE TITLE
[Bug]: Unable to delete account

### ISSUE THREAD

**Issue by mikeploythai** [pingdotgg/uploadthing#832]
### What happened?

After pressing the 'Delete Account' confirmation button, nothing happens. Upon inspecting the console, I saw the post request for account deletion returns a 403 and an error message saying "Self deletion is not enabled for this user". Refer to the images below.

<img width="471" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/110638329/03b05034-d242-4786-9b23-f4e32c9613f6">
<img width="912" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/110638329/8279c4ed-3dfa-4e78-96bc-fa3f7675814d">

### What did you expect to happen?

I should've been redirected to the landing page and have my account be inaccessible

### Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Oh no, I thought we had fixed that, can you let me know what GitHub account you are seeing this error with so that I can get it corrected?

**Comment by mikeploythai** [comment]
I'm seeing it through this GitHub account. If you'd like more information, such as the email associated with it, let me know what'd be a good way to share it privately with you.

**Comment by markflorkowski** [comment]
Ah found it. Should be fixed now. Let me know if you are still having trouble.

**Comment by mikeploythai** [comment]
Works properly now! Only bug remaining is in the navbar; the user icon and link to dashboard remains after deletion rather than switching to show the sign in button.

**Comment by markflorkowski** [comment]
Stale state will be fixed in an upcoming release.
